### ISSUE TITLE
能支持reader和writer吗

### ISSUE THREAD

**Issue by Nyx2022** [MeteorsLiu/fastcopy#1]
你好，golang中有io.Copy和io.CopyN方法，你这个库能支持对这两个函数的替换并且效率提高，占用降低吗

**Comment by MeteorsLiu** [comment]
你好，

这个项目旨在替换掉内置的copy函数，能不能提高你可以自己跑benchmark。

至于能不能支持，reader和writer一般来说不是固定的，因为它们只是interface，具体的取决于实现interface的结构体Read和Write函数。所以不能。因为reader和writer，只是接口，并没有实质函数。

总的来说，这个项目不是代替io.Copy的。请你看看io.Copy的说明。如果是TCP与TCP拷贝，我建议你用io.Copy，在Linux系统下，那个函数调用了Linux的Splice函数进行优化，Splice函数是内核级别的零拷贝，速度非常快

**Comment by Nyx2022** [comment]
> 你好，
> 
> 这个项目旨在替换掉内置的copy函数，能不能提高你可以自己跑benchmark。
> 
> 至于能不能支持，reader和writer一般来说不是固定的，因为它们只是interface，具体的取决于实现interface的结构体Read和Write函数。所以不能。因为reader和writer，只是接口，并没有实质函数。
> 
> 总的来说，这个项目不是代替io.Copy的。请你看看io.Copy的说明。如果是TCP与TCP拷贝，我建议你用io.Copy，在Linux系统下，那个函数调用了Linux的Splice函数进行优化，Splice函数是内核级别的零拷贝，速度非常快

好的，谢谢
